# Generated by Django 4.2.20 on 2025-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='componentgcp',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectgcp',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
